import type { GithubWebhookEventName } from "@/types/external/github";

export const SUPPORTED_GITHUB_EVENTS = [
  "branch_protection_rule",
  "check_run",
  "check_suite",
  "commit_comment",
  "create",
  "delete",
  "deploy_key",
  "deployment",
  "deployment_protection_rule",
  "deployment_review",
  "deployment_status",
  "discussion",
  "discussion_comment",
  "fork",
  "issue_comment",
  "issues",
  "label",
  "member",
  "merge_group",
  "milestone",
  "package",
  "page_build",
  "public",
  "pull_request",
  "pull_request_review",
  "pull_request_review_comment",
  "pull_request_review_thread",
  "push",
  "registry_package",
  "release",
  "repository",
  "status",
  "watch",
  "workflow_dispatch",
  "workflow_job",
  "workflow_run",
] as const satisfies readonly GithubWebhookEventName[];

export type SupportedGithubEventName = (typeof SUPPORTED_GITHUB_EVENTS)[number];
