import type { GithubWebhookEventName } from "@/types/external/github";

export const SUPPORTED_GITHUB_EVENTS = [
  "branch_protection_configuration",
  "branch_protection_rule",
  "check_run",
  "check_suite",
  "commit_comment",
  "create",
  "custom_property",
  "custom_property_values",
  "delete",
  "deploy_key",
  "deployment",
  "deployment_protection_rule",
  "deployment_review",
  "deployment_status",
  "discussion",
  "discussion_comment",
  "fork",
  "github_app_authorization",
  "gollum",
  "installation",
  "issue_comment",
  "issue_dependencies",
  "issues",
  "label",
  "member",
  "merge_group",
  "meta",
  "milestone",
  "package",
  "page_build",
  "project",
  "project_card",
  "project_column",
  "projects_v2",
  "projects_v2_item",
  "projects_v2_status_update",
  "public",
  "pull_request",
  "pull_request_review",
  "pull_request_review_comment",
  "pull_request_review_thread",
  "push",
  "registry_package",
  "release",
  "repository",
  "repository_dispatch",
  "repository_import",
  "repository_ruleset",
  "star",
  "status",
  "sub_issues",
  "team_add",
  "watch",
  "workflow_dispatch",
  "workflow_job",
  "workflow_run",
] as const satisfies readonly GithubWebhookEventName[];

export type SupportedGithubEventName = (typeof SUPPORTED_GITHUB_EVENTS)[number];
